// <auto-generated />
using System;
using FlightBite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightBite.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230904073811_ReInitialCreate")]
    partial class ReInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryMasterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ATOL")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ATOL");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EnquiryPlatformModelId")
                        .HasColumnType("int");

                    b.Property<int>("EnquiryStatusModelId")
                        .HasColumnType("int");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IATA");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("job_title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserTypesModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnquiryPlatformModelId");

                    b.HasIndex("EnquiryStatusModelId");

                    b.HasIndex("UserTypesModelId");

                    b.ToTable("EnquiryMaster");
                });

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryNoteDetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("EnquiryMasterModelId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EnquiryMasterModelId");

                    b.ToTable("EnquiryNoteDetail");
                });

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryPlatformModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("PlatForm")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("plat_form");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("EnquityPlatform");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 9, 4, 13, 8, 11, 492, DateTimeKind.Local).AddTicks(2950),
                            Description = "-",
                            PlatForm = "Google"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 9, 4, 13, 8, 11, 492, DateTimeKind.Local).AddTicks(2954),
                            Description = "-",
                            PlatForm = "Brochure"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 9, 4, 13, 8, 11, 492, DateTimeKind.Local).AddTicks(2958),
                            Description = "-",
                            PlatForm = "Other"
                        });
                });

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryStatusModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("EnquiryStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 9, 4, 13, 8, 11, 492, DateTimeKind.Local).AddTicks(3083),
                            Status = "In Progress"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 9, 4, 13, 8, 11, 492, DateTimeKind.Local).AddTicks(3086),
                            Status = "Complete"
                        });
                });

            modelBuilder.Entity("FlightBite.Data.Models.LogsMasterModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("class_name");

                    b.Property<string>("ClientApiAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("client_api_address");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("file_name");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("message");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("method");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("stack_track");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("LogsMaster");
                });

            modelBuilder.Entity("FlightBite.Data.Models.RequestLogsMasterModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("client_ip_address");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("created_at");

                    b.Property<string>("Request")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("request");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("response");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("RequestLogsMasters");
                });

            modelBuilder.Entity("FlightBite.Data.Models.RequestResponseLogsModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("client_ip_address");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("created_at");

                    b.Property<string>("Request")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("request");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("response");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("RequestResponseLogs");
                });

            modelBuilder.Entity("FlightBite.Data.Models.UserTypesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_type");

                    b.HasKey("Id");

                    b.ToTable("UserType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 9, 4, 13, 8, 11, 492, DateTimeKind.Local).AddTicks(3102),
                            Description = "-",
                            UserType = "Supplier"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 9, 4, 13, 8, 11, 492, DateTimeKind.Local).AddTicks(3104),
                            Description = "-",
                            UserType = "Travel Agent"
                        });
                });

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryMasterModel", b =>
                {
                    b.HasOne("FlightBite.Data.Models.EnquiryPlatformModel", "EnquiryPlatformModel")
                        .WithMany("EnquiryMasterModels")
                        .HasForeignKey("EnquiryPlatformModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBite.Data.Models.EnquiryStatusModel", "EnquiryStatusModel")
                        .WithMany("EnquiryMasterModels")
                        .HasForeignKey("EnquiryStatusModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBite.Data.Models.UserTypesModel", "UserTypesModel")
                        .WithMany("EnquiryMasterModels")
                        .HasForeignKey("UserTypesModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnquiryPlatformModel");

                    b.Navigation("EnquiryStatusModel");

                    b.Navigation("UserTypesModel");
                });

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryNoteDetailsModel", b =>
                {
                    b.HasOne("FlightBite.Data.Models.EnquiryMasterModel", "EnquiryMasterModel")
                        .WithMany("EnquiryNoteDetailsModel")
                        .HasForeignKey("EnquiryMasterModelId");

                    b.Navigation("EnquiryMasterModel");
                });

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryMasterModel", b =>
                {
                    b.Navigation("EnquiryNoteDetailsModel");
                });

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryPlatformModel", b =>
                {
                    b.Navigation("EnquiryMasterModels");
                });

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryStatusModel", b =>
                {
                    b.Navigation("EnquiryMasterModels");
                });

            modelBuilder.Entity("FlightBite.Data.Models.UserTypesModel", b =>
                {
                    b.Navigation("EnquiryMasterModels");
                });
#pragma warning restore 612, 618
        }
    }
}
