// <auto-generated />
using System;
using FlightBite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightBite.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryMasterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ATOL")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ATOL");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EnquiryPlatformId")
                        .HasColumnType("int")
                        .HasColumnName("enquiry_platform_id");

                    b.Property<int>("EnquiryStatusId")
                        .HasColumnType("int")
                        .HasColumnName("enquiry_status_id");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IATA");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("job_title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int")
                        .HasColumnName("user_type_id");

                    b.HasKey("Id");

                    b.HasIndex("EnquiryStatusId");

                    b.ToTable("EnquiryMaster");
                });

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryNoteDetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EnquiryId")
                        .HasColumnType("int")
                        .HasColumnName("enquiry_id");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("EnquiryNoteDetail");
                });

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryPlatformModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("EnquityPlatform");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4039),
                            Description = "-",
                            Name = "Google",
                            UpdatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4041)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4046),
                            Description = "-",
                            Name = "Brochure",
                            UpdatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4047)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4049),
                            Description = "-",
                            Name = "Other",
                            UpdatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4049)
                        });
                });

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryStatusModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("EnquiryStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4188),
                            Status = "In Progress",
                            UpdatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4188)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4190),
                            Status = "Complete",
                            UpdatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4191)
                        });
                });

            modelBuilder.Entity("FlightBite.Data.Models.LogsMasterModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("class_name");

                    b.Property<string>("ClientApiAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("client_api_address");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("file_name");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("message");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("method");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("stack_track");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("LogsMaster");
                });

            modelBuilder.Entity("FlightBite.Data.Models.RequestLogsMasterModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("client_ip_address");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("created_at");

                    b.Property<string>("Request")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("request");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("response");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("RequestLogsMasters");
                });

            modelBuilder.Entity("FlightBite.Data.Models.RequestResponseLogsModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("client_ip_address");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("created_at");

                    b.Property<string>("Request")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("request");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("response");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("RequestResponseLogs");
                });

            modelBuilder.Entity("FlightBite.Data.Models.UserTypesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("UserType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4204),
                            Description = "-",
                            Type = "Supplier",
                            UpdatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4205)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4207),
                            Description = "-",
                            Type = "Agent",
                            UpdatedAt = new DateTime(2023, 8, 19, 13, 20, 39, 998, DateTimeKind.Local).AddTicks(4208)
                        });
                });

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryMasterModel", b =>
                {
                    b.HasOne("FlightBite.Data.Models.EnquiryStatusModel", "EnquiryStatus")
                        .WithMany("EnquiryMaster")
                        .HasForeignKey("EnquiryStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnquiryStatus");
                });

            modelBuilder.Entity("FlightBite.Data.Models.EnquiryStatusModel", b =>
                {
                    b.Navigation("EnquiryMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
